FROM node:17-bullseye-slim as builder

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG VITE_SERVER_URL
ENV VITE_SERVER_URL "$VITE_SERVER_URL"
RUN npm run build

# Copy the files to nginx.
FROM nginx:1.21.6-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
