version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - VITE_SERVER_URL=https://unsaferust.org/api/v1
    ports:
      - ${CLIENT_PORT:-3000}:80
    env_file:
      - .env
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - ${SERVER_PORT:-3001}:${SERVER_PORT:-3001}
    volumes:
      # This is for development
      - /tmp/rust_projects:/tmp/rust_projects

      # This is needed for live projects updates
      - ./server/data:/app/data
    env_file:
      - .env
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
    # Todo: Add health check
    depends_on:
      - db

  db:
    # The bullseye creates correct sorting compared to alpine.
    image: postgres:14-bullseye
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
