version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}
    volumes:
      - ./client/src:/app/src
    env_file:
      - .env
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - VITE_SERVER_URL=http://127.0.0.1:3001/api/v1
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT:-3001}:${SERVER_PORT:-3001}
    volumes:
      - ./server/src:/app/src
      # This is for development
      - /tmp/rust_projects:/tmp/rust_projects
    env_file:
      - .env
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
    # Todo: Add health check
    depends_on:
      - db

  db:
    # The bullseye creates correct sorting compared to alpine.
    image: postgres:14-bullseye
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
