version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: ${RESTART_POLICY:-unless-stopped}

  db:
    # The bullseye creates correct sorting compared to alpine.
    image: postgres:14-bullseye
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: ${RESTART_POLICY:-unless-stopped}
    #    volumes:
    #      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - redis

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT:-3001}:${SERVER_PORT:-3001}
    volumes:
      - ./server/src:/app/src
      - ./server/tests:/app/tests
      - ./server/migrations:/app/migrations
      # This is for development
      - /tmp/rust_projects:/tmp/rust_projects

      # This is needed for live projects updates
      - ./server/data:/app/data
    env_file:
      - .env
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=services
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      # This is for https://crates.io/crates/sqlx-cli
      - DATABASE_URL=postgres://postgres@${DB_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}
    volumes:
      - ./client/src:/app/src
    env_file:
      - .env
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - VITE_SERVER_URL=http://127.0.0.1:3001/api/v1
    depends_on:
      - server

volumes:
  pgdata:
